name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker images
      run: |
        docker build -t gcr.io/$PROJECT_ID/app:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/app:${{ github.sha }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Deploy to Google Kubernetes Engine
      run: |
        kubectl set image deployment/app app=gcr.io/$PROJECT_ID/app:${{ github.sha }}
        kubectl rollout status deployment/app

    - name: Update database schema
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Please provide the correct command to run Alembic migrations
        # Example: alembic upgrade head
        echo "Run Alembic migrations here"

    - name: Run post-deployment health checks
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Please provide the correct health check endpoints and commands
        # Example: curl http://your-app-url/health
        echo "Run health checks here"